# version: '3.8'

# services:
#   # REDIS
#   redis:
#     image: "redis:7.0.11-alpine"

#   # DATABASE
#   postgres:
#     image: "postgres:14-alpine"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=prodigy
#       - POSTGRES_DB=rank

#   # WEB SERVICE
#   web:
#     build: .
#     command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "run.py", "runserver", "0.0.0.0:8001"]
#     depends_on:
#       - postgres
#       - redis
#     ports:
#       - "8000:8001"
#     environment:
#       - DEBUG=1
#       - SECRET_KEY=3ertyu8ifndasou9fijnfodl
#       - DATABASE_URL=postgres://postgres:prodigy@postgres:5432/rankd
#     volumes:
#       - .:/code  

# volumes:
#   postgres_data:
