version: '3.3'

services:
  # REDIS
  redis:
    image: "redis:7.0.11-alpine"
    container_name: "redis"
    command: redis-server --save 20 1 --loglevel warning
    privileged: true
    ports:
      - '6378:6379'

  # CELERY WORKER
  celery_worker:
    build: .
    command: celery -A rank worker --loglevel=INFO
    depends_on:
      - redis
    environment:
      - CELERY_URL=redis://redis:6379/0
    volumes:
      - .:/code

  # DATABASE
  db:
    image: "postgres:14-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=alpha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prodigy

  # WEB SERVICE
  web:
    build: .
    command: >
      sh -c "python run.py migrate &&
      python run.py create_public_tenant &&
      python run.py runserver 0.0.0.0:8001"

    depends_on:
      - db
      - redis
    ports:
      - "8000:8001"
    environment:
      - DEBUG=0
    volumes:
      - .:/code

    env_file:
      - .env.serve

volumes:
  postgres_data:

