# Generated by Django 4.2.4 on 2024-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Some content about user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian'), ('admin', 'Admin'), ('cleaner', 'Cleaner'), ('librarian', 'Librarian'), ('driver', 'Driver'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('security', 'Security'), ('nurse', 'Nurse'), ('counselor', 'Counselor'), ('other', 'Other')], max_length=50, null=True, verbose_name='User role'),
        ),
    ]
