# Generated by Django 4.2.4 on 2024-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian')], max_length=50, null=True, verbose_name='User role'),
        ),
    ]
