# Generated by Django 4.2.4 on 2023-10-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user email is verified ', verbose_name='email_verified'),
        ),
    ]
