# Generated by Django 4.2.4 on 2025-03-24 13:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('core', '0002_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMaterial',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the material being uploaded')),
                ('category', models.CharField(choices=[('book', 'Book'), ('merchandise', 'Merchandise'), ('past question', 'PastQuestion'), ('tutorial', 'Tutorial')], max_length=255, verbose_name='Category Item belong e.g Book, Handout')),
                ('doc', models.FileField(upload_to='material', validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'docx'])])),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Describe your content')),
                ('price', models.FloatField(default=0, verbose_name='Price of the material')),
                ('sold', models.IntegerField(default=0, verbose_name='Number of copies of this item sold')),
                ('is_global', models.BooleanField(verbose_name='If this item should be global and accessed in other schools')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='Can others save this material to their devices')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prefered_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.level')),
            ],
            options={
                'verbose_name': 'SchoolMaterial',
                'verbose_name_plural': 'SchoolMaterial',
                'ordering': ('sold',),
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.schoolmaterial')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('core.basemodel',),
        ),
    ]
