# Generated by Django 4.2.4 on 2024-03-16 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmaterial',
            name='prefered_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.level'),
        ),
        migrations.AddField(
            model_name='customer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.schoolmaterial'),
        ),
    ]
