# Generated by Django 4.2.4 on 2024-02-28 11:55

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_user_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('commercial', 'Commercial'), ('Other', 'Other')], max_length=255, verbose_name='Education type e.g General, Technical')),
                ('language_supports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='List of languages that the school uses'), default=list, size=None)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Date event is expected to start')),
                ('end_date', models.DateField(verbose_name='Date event ends')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('type', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], max_length=256, verbose_name='guardian type e.g Mother, Aunty, cousin')),
                ('alt_mail', models.EmailField(max_length=256)),
                ('city', models.CharField(max_length=256, verbose_name='City/town of residence of guardian')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('middleschool', 'Middleschool'), ('juniorhigh', 'JuniorHigh'), ('highschool', 'Highschool')], max_length=50, verbose_name='Levels in the school e.g Elementary, primary or secondary ')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.department')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Paypal email address')),
                ('bank', models.CharField(blank=True, max_length=256, null=True, verbose_name='Bank account')),
                ('swift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift code for bank')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account number in bank')),
                ('mtn_momo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile money number')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.schoolbasemodel')),
                ('name', models.CharField(max_length=2560, verbose_name='School Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dean of School')),
                ('principal_email', models.CharField(blank=True, max_length=100, null=True)),
                ('director_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Director of School')),
                ('director_email', models.CharField(blank=True, max_length=100, null=True)),
                ('director_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.SlugField(editable=False, unique=True)),
                ('city', models.CharField(max_length=100, verbose_name='Region of school')),
                ('address', models.CharField(max_length=256, verbose_name='School Location')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='School type e.g Elementary, Primary etc...')),
                ('report_card', models.CharField(blank=True, max_length=100, null=True, verbose_name='String identifying selected report card design')),
                ('billing_method', models.CharField(max_length=50, verbose_name='selected payment method e.g paypal or MTN')),
                ('active', models.BooleanField(default=False, verbose_name='School server is active')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('promo', 'Promo')], default='Free', max_length=20, verbose_name='Plan school is subscribed to e.g Free, standard or premium')),
                ('verification_doc', models.FileField(blank=True, null=True, upload_to='document', validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'docx'])])),
                ('is_verified', models.BooleanField(default=False, verbose_name='Sets if school document is valid')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this school subscription currently active')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School',
            },
            bases=('core.schoolbasemodel',),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='https://fb.com/tiidel', max_length=150, verbose_name='facebook profile link')),
                ('twitter', models.CharField(default='https://x.com/tiidel', max_length=150, verbose_name='twitter profile link')),
                ('instagram', models.CharField(default='https://instagram.com/tiidel', max_length=150, verbose_name='instagram profile link')),
                ('linkedin', models.CharField(default='https://linkedin.com/tiidel', max_length=150, verbose_name='linkedin profile link')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian')], max_length=256, verbose_name='type e.g Teacher, Administrator')),
                ('expirience', models.IntegerField(default=0, verbose_name='Years of expirience in post')),
                ('city', models.CharField(max_length=256, verbose_name='City/town of residence of guardian')),
                ('billing_method', models.CharField(max_length=50, verbose_name='Prefered payment method e.g paypal or MTN')),
                ('bio', models.CharField(blank=True, max_length=3000)),
                ('salary', models.IntegerField(default=0, verbose_name='salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='If staff member is currently active in their role')),
                ('recruit_date', models.DateField(blank=True, null=True, verbose_name='When they commenced work at the role ')),
                ('days_without_pay', models.IntegerField(default=0, verbose_name='Number of days since staff was payed')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.paymentdetail', verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_coef', models.IntegerField(default=1, verbose_name='Value of the subject (coefficient)')),
                ('course_duration', models.IntegerField(verbose_name='number of hours')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.level')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
                ('subject', models.ManyToManyField(default=None, related_name='subjects', to='school.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': ('Teacher',),
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='instructor',
            field=models.ManyToManyField(related_name='teacher', to='school.teacher'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Marital status')),
                ('bio', models.CharField(blank=True, max_length=3000)),
                ('adm_status', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=256)),
                ('admission_date', models.DateField(auto_now_add=True, verbose_name='Date person was admitted as a student')),
                ('place_of_birth', models.CharField(blank=True, max_length=256, null=True, verbose_name='Location where student was borne')),
                ('is_repeater', models.BooleanField(default=False, verbose_name='Student has repeated this class')),
                ('is_new_student', models.BooleanField(default=True, verbose_name='Is this a transfer or new student in this school')),
                ('guardians', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardians', to='school.guardian')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SchoolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='media/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('fee_type', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.IntegerField()),
                ('depositor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Names of user paying the fees')),
                ('is_complete', models.BooleanField(default=False)),
                ('installment', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('complete', 'Complete')], max_length=50, verbose_name='fee installment. partial or complete')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Given a school calendar, the date registration expires')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date school starts')),
                ('academic_end', models.DateField(verbose_name='Date school closes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Date program should terminate')),
                ('event', models.ManyToManyField(to='school.event', verbose_name='name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('recipient_name', models.CharField(max_length=300, verbose_name='Full names of user you want to invite')),
                ('recipient_email', models.EmailField(max_length=50, verbose_name='Email of users to send invititations to')),
                ('invite_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='State of the invitation')),
                ('tenant_name', models.CharField(max_length=50, verbose_name='School you are sending invites to')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian')], max_length=100, verbose_name='This refers to the role you are inviting the member for')),
                ('invitation_code', models.SlugField(editable=False, unique=True)),
                ('message', models.TextField(blank=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
            bases=('core.basemodel',),
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='e.g form one or lower sixth')),
                ('enrolment', models.IntegerField(default=0)),
                ('class_range', models.CharField(max_length=50, verbose_name='Approximate number of students in class')),
                ('h_o_d', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.level')),
            ],
        ),
    ]
