# Generated by Django 4.2.4 on 2024-05-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.CreateModel(
            name='MatriculeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('tenant', 'level')},
            },
        ),
    ]
