# Generated by Django 4.2.4 on 2024-04-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payments',
            field=models.ManyToManyField(null=True, related_name='registrationPayment', to='school.payment'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ClassFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.IntegerField(verbose_name='Total amount of money to be payed by students in this class')),
                ('first_installment', models.IntegerField(verbose_name='First installment of this fee')),
                ('second_installment', models.IntegerField(blank=True, null=True, verbose_name='Second installment of this fee')),
                ('third_installment', models.IntegerField(blank=True, null=True, verbose_name='Third installment of this fee')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
            ],
            options={
                'verbose_name': ('class Fee',),
                'verbose_name_plural': 'class Fees',
            },
        ),
    ]
