# Generated by Django 4.2.4 on 2024-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_list',
            field=models.ManyToManyField(related_name='student_rank_grades', to='school.studentsubjects'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
