# Generated by Django 4.2.4 on 2024-04-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='school',
        ),
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.program'),
            preserve_default=False,
        ),
    ]
