# Generated by Django 4.2.4 on 2024-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian')], max_length=256, verbose_name='type e.g Teacher, Administrator'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
                ('subject', models.ManyToManyField(default=None, related_name='subjects', to='school.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': ('Teacher',),
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='instructor',
            field=models.ManyToManyField(related_name='teacher', to='school.teacher'),
        ),
    ]
