# Generated by Django 4.2.4 on 2024-05-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='terms',
            field=models.ManyToManyField(null=True, to='school.terms', verbose_name='program_terms'),
        ),
    ]
