# Generated by Django 4.2.4 on 2024-03-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='classes', to='school.subject'),
        ),
    ]
