# Generated by Django 4.2.4 on 2024-03-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='event',
            new_name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='school',
        ),
        migrations.AddField(
            model_name='event',
            name='programs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.program'),
            preserve_default=False,
        ),
    ]
