# Generated by Django 4.2.4 on 2024-03-03 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_alter_staff_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='e.g +237 or +1'),
        ),
        migrations.CreateModel(
            name='SchoolStaffApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=256, verbose_name='Role he/she is applying for')),
                ('tenant', models.CharField(max_length=50, verbose_name='School you are applying into')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Displays whether or not user is accepted into school')),
                ('hidden', models.BooleanField(default=False, verbose_name='Whether or not admin wants this to display')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_status', models.CharField(choices=[('active', 'Active'), ('new', 'New'), ('accepted', 'Accepted'), ('Low', 'Low'), ('unqualified', 'Unqualified')], default='active', max_length=256, verbose_name='Checks whether or not user is actively searching')),
                ('role', models.CharField(max_length=256, verbose_name='Role he/she is applying for')),
                ('cv', models.FileField(upload_to='applicant_cv', validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'docx'])])),
                ('summary', models.CharField(max_length=5000, verbose_name='Summary of job application')),
                ('tenant', models.CharField(blank=True, max_length=50, null=True, verbose_name='School you are applying into')),
                ('country', models.CharField(blank=True, max_length=500, null=True, verbose_name='Country of origin of applicant')),
                ('rejection_count', models.IntegerField(default=0, verbose_name='Number of times the applicant has been rejected')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of application')),
                ('interview_date', models.DateTimeField(blank=True, null=True, verbose_name='Date and time of interview')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Years of experience')),
                ('references', models.TextField(blank=True, null=True, verbose_name='References')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected Salary')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback provided by the interviewer')),
                ('meeting_url', models.URLField(blank=True, null=True, verbose_name='URL for the interview meeting')),
                ('is_hired', models.BooleanField(default=False, verbose_name='Applicant has been hired for the position')),
                ('rejected', models.BooleanField(default=False, verbose_name='If the applicant has been rejected from the school')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
