# Generated by Django 4.2.4 on 2023-09-16 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_event_remove_level_department_remove_student_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Paypal email address')),
                ('bank', models.CharField(blank=True, max_length=256, null=True, verbose_name='Bank account')),
                ('swift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift code for bank')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account number in bank')),
                ('mtn_momo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile money number')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date school starts')),
                ('academic_end', models.DateField(verbose_name='Date school closes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Date program should terminate')),
                ('event', models.ManyToManyField(to='school.event', verbose_name='name')),
            ],
        ),
    ]
