# Generated by Django 4.2.4 on 2024-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_timetable_class_instance_matriculecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='daysOfWeek',
            field=models.JSONField(default=list, verbose_name='Days of the week as integers'),
        ),
    ]
