# Generated by Django 4.2.4 on 2024-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_program_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='academic_end',
            field=models.DateField(verbose_name='Date school closes'),
        ),
        migrations.AlterField(
            model_name='program',
            name='academic_start',
            field=models.DateField(verbose_name='Date school starts'),
        ),
        migrations.AlterField(
            model_name='program',
            name='terms',
            field=models.ManyToManyField(to='school.terms', verbose_name='program_terms'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date sequence starts'),
        ),
    ]
