# Generated by Django 4.2.4 on 2024-03-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjects',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.terms'),
        ),
        migrations.AddField(
            model_name='terms',
            name='term_validated',
            field=models.BooleanField(default=False, verbose_name='If the term has been validated'),
        ),
    ]
