# Generated by Django 4.2.4 on 2024-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_registration_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_status',
            field=models.CharField(choices=[('none', 'None'), ('first', 'First'), ('second', 'Second'), ('complete', 'Complete')], max_length=50, verbose_name='fee installment. partial or complete'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='start_date',
            field=models.DateField(verbose_name='Date term starts'),
        ),
    ]
