# Generated by Django 4.2.4 on 2024-04-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_event_program_events_remove_event_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='classes', to='school.subject'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Date program should terminate'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Day of the week')),
                ('start_time', models.TimeField(verbose_name='Time the class starts')),
                ('end_time', models.TimeField(verbose_name='Time the class ends')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.terms')),
            ],
            options={
                'verbose_name': 'TimeTable',
                'verbose_name_plural': 'TimeTables',
            },
        ),
    ]
