# Generated by Django 4.2.4 on 2024-04-14 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_grade_grade_list_alter_grade_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-average']},
        ),
        migrations.RemoveField(
            model_name='studentsubjects',
            name='first_seq',
        ),
        migrations.RemoveField(
            model_name='studentsubjects',
            name='second_seq',
        ),
        migrations.RemoveField(
            model_name='studentsubjects',
            name='terms',
        ),
        migrations.AddField(
            model_name='studentsubjects',
            name='grade',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade'),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the sequence e.g first sequence, second sequence')),
                ('start_date', models.DateField(auto_now_add=True, null=True, verbose_name='Date sequence starts')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date sequence ends')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='school.terms')),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
            },
        ),
        migrations.AddField(
            model_name='studentsubjects',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sequence'),
        ),
    ]
