# Generated by Django 4.2.4 on 2024-03-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
    ]
