# Generated by Django 4.2.4 on 2023-09-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_paymentdetail_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('billing_method', models.CharField(max_length=50, verbose_name='selected payment method e.g paypal or MTN')),
                ('server_type', models.CharField(default='free', max_length=50, verbose_name='Type of server registered')),
                ('active', models.BooleanField(default=False, verbose_name='School server is active')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.paymentdetail', verbose_name='')),
            ],
        ),
    ]
