# Generated by Django 4.2.4 on 2024-05-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_timetable_daysofweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
