# Generated by Django 4.2.4 on 2024-04-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_registration_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
