# Generated by Django 4.2.4 on 2024-04-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_grade_options_remove_studentsubjects_first_seq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='term',
        ),
        migrations.AddField(
            model_name='grade',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sequence'),
        ),
    ]
