# Generated by Django 4.2.4 on 2024-02-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_id_teacher_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='id',
        ),
    ]
