# Generated by Django 4.2.4 on 2024-04-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_grade_term_grade_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='sequence',
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.terms'),
        ),
    ]
