# Generated by Django 4.2.4 on 2024-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_end_time_timetable_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
