# Generated by Django 4.2.4 on 2023-09-16 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_department_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=256)),
                ('last_names', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('phone', models.CharField(max_length=20)),
                ('job', models.CharField(verbose_name='type e.g Teacher, Administrator')),
                ('expirience', models.IntegerField(default=0, verbose_name='Years of expirience in post')),
                ('city', models.CharField(max_length=256, verbose_name='City/town of residence of guardian')),
                ('address', models.CharField(max_length=256, verbose_name='location of residence of guardian/parent')),
                ('billing_method', models.CharField(max_length=50, verbose_name='selected payment method e.g paypal or MTN')),
                ('bio', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='modification to profile')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.paymentdetail', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_coef', models.IntegerField(default=1, verbose_name='Value of the subject (coefficient)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.level')),
                ('instructor', models.ManyToManyField(related_name='subjects', to='school.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.ManyToManyField(default=None, related_name='instructors', to='school.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
