# Generated by Django 4.2.4 on 2024-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_payment_transaction_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='expected_ammount',
            field=models.IntegerField(null=True, verbose_name='The amount student is expected to pay for the class'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_status',
            field=models.CharField(choices=[('none', 'None'), ('first', 'First'), ('second', 'Second'), ('complete', 'Complete')], max_length=50, null=True, verbose_name='fee installment. partial or complete'),
        ),
    ]
