# Generated by Django 4.2.4 on 2024-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_grade_sequence_grade_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='alt_mail',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='City/town of residence of guardian'),
        ),
    ]
