# Generated by Django 4.2.4 on 2024-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_guardian_alt_mail_alter_guardian_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='student',
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ManyToManyField(related_name='guardian_student_list', to='school.student'),
        ),
    ]
