# Generated by Django 4.2.4 on 2023-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_staff_subject_staff_subject_staff_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.ManyToManyField(default=None, related_name='subjects', to='school.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='instructor',
            field=models.ManyToManyField(related_name='teacher', to='school.staff'),
        ),
    ]
