# Generated by Django 4.2.4 on 2023-09-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0007_alter_staff_subject_alter_subject_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=256)),
                ('last_names', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50, verbose_name='Marital status')),
                ('student_class', models.CharField(max_length=256)),
                ('bio', models.CharField(blank=True, max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('adm_status', models.CharField(default=0)),
                ('department', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('guad_name', models.CharField(max_length=256)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='modification to profile')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.IntegerField()),
                ('depositor', models.CharField(blank=True, max_length=20, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('installment', models.CharField(max_length=50, verbose_name='fee installment. partial or complete')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Given a school calendar, the date registration expires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='installment update')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.level')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
