# Generated by Django 4.2.4 on 2024-06-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_class_formal_name_alter_subscription_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='e.g form one or lower sixth'),
        ),
        migrations.AddField(
            model_name='class',
            name='promotion_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='siblings',
            field=models.ManyToManyField(null=True, related_name='class_siblings', to='school.class'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('Middle School', 'Middle School'), ('form', 'Form'), ('Junior High', 'Junior High'), ('High School', 'High School')], max_length=50, verbose_name='Levels in the school e.g Elementary, primary or secondary '),
        ),
    ]
