# Generated by Django 4.2.4 on 2024-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_class_full_name_class_promotion_class_class_siblings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='formal_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='e.g form one or lower sixth'),
        ),
    ]
