# Generated by Django 4.2.4 on 2023-09-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=256)),
                ('last_names', models.CharField(max_length=256)),
                ('type', models.CharField(verbose_name='guardian type e.g Mother, Aunty, cousin')),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=256, verbose_name='City/town of residence of guardian')),
                ('address', models.CharField(max_length=256, verbose_name='location of residence of guardian/parent')),
                ('address_two', models.CharField(blank=True, max_length=256, null=True, verbose_name='location of residence of guardian/parent')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='modification to profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
