# Generated by Django 4.2.4 on 2023-09-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_guardian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_names',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_names',
            new_name='last_name',
        ),
    ]
