# Generated by Django 4.2.4 on 2024-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_class_formal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bank_account',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='staff',
            name='swift_code',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian'), ('admin', 'Admin'), ('cleaner', 'Cleaner'), ('librarian', 'Librarian'), ('driver', 'Driver'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('security', 'Security'), ('nurse', 'Nurse'), ('counselor', 'Counselor'), ('other', 'Other')], max_length=100, verbose_name='This refers to the role you are inviting the member for'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('student', 'Student'), ('guardian', 'Guardian'), ('admin', 'Admin'), ('cleaner', 'Cleaner'), ('librarian', 'Librarian'), ('driver', 'Driver'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('security', 'Security'), ('nurse', 'Nurse'), ('counselor', 'Counselor'), ('other', 'Other')], max_length=256, verbose_name='type e.g Teacher, Administrator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Maximum qualification of student'),
        ),
    ]
